version: 1.0.{build}
environment:
  configuration: Debug
  COVERALLS_REPO_TOKEN:
    secure: sAoqj4mz8jCeeQ0em98Z0KAJZubVl0Q76cqb6ZH/2rgzFmaNM7Z3GplBlh+p60xQ
before_build:
- cmd: nuget restore
build:
  project: Delta.Units.sln
  verbosity: normal 
test_script:
- ps: '& .\unit-tests.ps1'
artifacts:
- path: Delta.Units\bin\$(configuration)\Delta.Units.dll
  name: Binaries
- path: opencoverCoverage.xml
  name: Coverage
  
